export {
  REGION_MAP_COUNTRY_ALIASES,
  REGION_MAP_FEATURES_BY_KEY,
  REGION_MAP_US_STATE_ALIASES,
  REGION_MAP_US_STATE_FEATURES_BY_KEY,
  US_STATE_FEATURES,
  US_STATE_NAME_BY_ID,
  WORLD_COUNTRY_FEATURES,
  buildRegionMapLegendItems,
  getRegionMapBaseFeatures,
  normalizeRegionMapKey,
  resolveRegionMapBaseColor,
  resolveRegionMapColorStrings,
  resolveRegionMapDataColor,
  resolveRegionMapFeature,
  resolveRegionMapFeatureSet,
  resolveRegionMapLayoutProperties,
  resolveRegionMapNoDataColor,
  resolveRegionMapValueColor,
  resolveRegionMapValueColorFromStops,
  resolveRegionMapValueColors,
} from "../render/chart-region-map";
