// DOCX Vue components barrel.
// Architecture: §3.2 components/ — 18 Vue component files.

export { default as DocxViewer } from "./DocxViewer.vue"
export { default as DocxEditor } from "./DocxEditor.vue"
export { default as DocxViewerRoot } from "./DocxViewerRoot.vue"
export { default as DocxPageWrapper } from "./DocxPageWrapper.vue"
export { default as DocxPageSurface } from "./DocxPageSurface.vue"
export { default as DocxPageHeader } from "./DocxPageHeader.vue"
export { default as DocxPageFooter } from "./DocxPageFooter.vue"
export { default as DocxPageBody } from "./DocxPageBody"
export { default as DocxParagraphHost } from "./DocxParagraphHost.vue"
export { default as DocxTableHost } from "./DocxTableHost.vue"
export { default as DocxImageLayer } from "./DocxImageLayer.vue"
export { default as DocxFormFieldLayer } from "./DocxFormFieldLayer.vue"
export { default as DocxTrackedChangeGutter } from "./DocxTrackedChangeGutter.vue"
export { default as DocxContextMenu } from "./DocxContextMenu.vue"
export { default as DocxToolbar } from "./DocxToolbar.vue"
export { default as DocxThumbnailPanel } from "./DocxThumbnailPanel.vue"
export { default as DocxDragOverlay } from "./DocxDragOverlay.vue"
